name: using-eslint-on-push
on: push
jobs:
  eslint:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: make eslint
